// URL: https://leetcode.com/problems/lexicographically-smallest-generated-string/
// Difficulty: Hard
//
// Problem:
// You are given two strings, str1 and str2, of lengths n and m, respectively.
//
// A string `word` of length n + m - 1 is defined to be **generated** by str1 and str2
// if it satisfies the following conditions for each index 0 <= i <= n - 1:
//
//   - If str1[i] == 'T', the substring of word with size m starting at index i is
//     equal to str2, i.e., word[i..(i + m - 1)] == str2.
//   - If str1[i] == 'F', the substring of word with size m starting at index i is
//     NOT equal to str2, i.e., word[i..(i + m - 1)] != str2.
//
// Return the lexicographically smallest possible string that can be generated by
// str1 and str2. If no string can be generated, return an empty string "".
//
// Example 1:
//   Input:  str1 = "TFTF", str2 = "ab"
//   Output: "ababa"
//   Explanation:
//     Index 0 ('T'): word[0..1] == "ab"  ✓
//     Index 1 ('F'): word[1..2] == "ba" != "ab"  ✓
//     Index 2 ('T'): word[2..3] == "ab"  ✓
//     Index 3 ('F'): word[3..4] == "ba" != "ab"  ✓
//     "ababa" and "ababb" are both valid; "ababa" is lexicographically smaller.
//
// Example 2:
//   Input:  str1 = "TFTF", str2 = "abc"
//   Output: ""
//   Explanation: No string satisfying the conditions can be generated.
//
// Example 3:
//   Input:  str1 = "F", str2 = "d"
//   Output: "a"
//
// Constraints:
//   1 <= n == str1.length <= 10^4
//   1 <= m == str2.length <= 500
//   str1 consists only of 'T' or 'F'.
//   str2 consists only of lowercase English characters.

#include <string>
#include <unordered_set>
#include <vector>
using namespace std;

class Solution {
public:
    std::vector<int> buildFailure(const string& s) {
        int n = s.size();
        int len = 0;
        int i = 1;
        std::vector<int> fail(n, 0);

        while (i < n) {
            if (s[i] == s[len]) {
                fail[i++] = ++len;
            } else if (len > 0) {
                len = fail[len - 1];
            } else {
                fail[i++] = 0;
            }
        }

        return fail;
    }

    std::unordered_set<int> validOverlaps(const std::vector<int>& fail, int m) {
        std::unordered_set<int> valid{};

        int len = fail[m - 1];

        while (len > 0) {
            valid.insert(len);
            len = fail[len - 1];
        }

        return valid;
    }
    
    string generateString(string str1, string str2) {
        const int n = str1.length();
        const int m = str2.length();
        
        string result(str1.length() + str2.length() - 1, 'a');
        std::vector<int> fail = buildFailure(str2);
        std::vector<int> diff(n + m, 0);
        std::vector<bool> covered(n + m - 1, false);
        std::unordered_set<int> valid = validOverlaps(fail, str2.length());

        int prevT = -1;

        // first pass, only T
        for (int i = 0; i < str1.size(); i++) {
            char c = str1[i];

            if (c == 'F') {
                continue;
            }

            diff[i]++;
            diff[i + m]--;

            for (int j = 0; j < m; j++) {
                result[i + j] = str2[j];
            }

            if (prevT != -1 && i - prevT < m) {
                int overlap = m - (i - prevT);

                if (!valid.count(overlap)) {
                    return "";
                }
            }

            prevT = i;
        }

        int running = 0;

        for (int p = 0; p < n + m - 1; p++) {
            running += diff[p];
            covered[p] = running > 0;
        }

        // second pass, only F
        for (int i = 0; i < n; i++) {
            char c= str1[i];

            if (c == 'T') {
                continue;
            }

            if (result.substr(i, m) != str2) {
                continue;
            }

            int freePos = -1;

            for (int j = i + m - 1; j >= i; j--) {
                if (!covered[j]) {
                    freePos = j;
                    break;
                }
            }

            if (freePos == -1) {
                return "";
            }

            char insert = str2[freePos - i];
            result[freePos] = (insert == 'a') ? 'b' : 'a';
        }
        
        return result;
    }
};

int main() { return 0; }
